version: '3'
services:
  control:
    build: .
    container_name: control
    hostname: control
    volumes:
      - .:/root/ansible
  node1:
    build: .
    container_name: node1
    hostname: node1